server:
  port: 7012
spring:
  application:
    name: jeecg-cbir
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
  rabbitmq:
    host: 10.3.15.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /