server:
  port: 7011
spring:
  application:
    name: jeecg-sample
#  #postgresql 报错问题
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:

          url: jdbc:mysql://jeecg-boot-mysql:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 多数据源配置
        postgis:
          url: jdbc:postgresql://postgis:5433/rss_sample_center
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
  rabbitmq:
    host: 10.3.15.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
mybatis:
  mapper-locations: classpath:org/jeecg/modules/sample/mapper/xml/*.xml
  type-aliases-package: org.jeecg.modules.sample.entity  #所有entity别名所在包
  type-handlers-package: org.jeecg.modules.sample.handler
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#hystrix的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 3000000
        readTimeout: 3000000
  hystrix:
    enabled: false
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000000
  ConnectTimeout: 3000000
logging:
  level:
    org.apache.ibatis: WARN
    org.mybatis.spring: WARN
    org.jeecg.modules.sample.mapper: WARN
    com:
      baomidou:
        mybatisplus: INFO
    org:
      mybatis: INFO
